global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'tempo'
    static_configs:
    - targets: ['tempo:3100']

  - job_name: 'loki'
    static_configs:
    - targets: ['loki:3100']

  - job_name: 'order-service-otel'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['order-service-otel:8080']

  - job_name: 'shipping-service-otel'
    metrics_path: /actuator/prometheus
    static_configs:
    - targets: ['shipping-service-otel:8081']
