apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: order-service
spec:
  host: order-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
    trafficPolicy:
        connectionPool:
         http:
            http1MaxPendingRequests: 1
            maxRequestsPerConnection: 1
         tcp:
            maxConnections: 1 
        outlierDetection:
          consecutiveErrors: 2
          interval: 1m
          baseEjectionTime: 5m
          maxEjectionPercent: 100