apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: profile-service
spec:
  host: profile-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2