version: "3.8"

services:

  loki:
    image: grafana/loki:2.2.0
    command: -config.file=/etc/loki/loki-local.yaml
    ports:
      - "3101:3100"                                   
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./configs/loki/loki-local.yaml:/etc/loki/loki-local.yaml
      - ./data/loki-data:/tmp/loki

  tempo:
    image: grafana/tempo:0.7.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./configs/tempo/tempo-local.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/tmp/tempo
    restart: unless-stopped  
    ports:
      - "14268:14268"  # jaeger ingest, Jaeger - Thrift HTTP
      - "14250:14250"  # Jaeger - GRPC
      - "55680:55680"  # OpenTelemetry
      - "3102:3100"   # tempo

  tempo-query:
    image: grafana/tempo-query:0.7.0
    command: ["--grpc-storage-plugin.configuration-file=/etc/tempo-query.yaml"]
    volumes:
      - ./configs/tempo/tempo-query.yaml:/etc/tempo-query.yaml
    ports:
      - "16686:16686"  # jaeger-ui
    depends_on:
      - tempo

  order-service-otel:
    image: "sinhasonalkumar/order-service-otel:v1"
    ports:
      - "8080:8080"
    environment:
      - orderservice.client.shippingservice.base.url=http://shipping-service-otel:8081/shipping-service
      - otel.traces.exporter=jaeger
      - otel.exporter.jaeger.endpoint=http://tempo:14250
      - otel.metrics.exporter=none
      - otel.javaagent.debug=false
      - otel.resource.attributes=service.name=order-service-otel
    volumes:
      - ./data/applications/logs:/app/logs
    depends_on:
      - tempo

  shipping-service-otel:
    image: "sinhasonalkumar/shipping-service-otel:v1"
    ports:
      - "8081:8081"
    environment:
      - otel.traces.exporter=jaeger
      - otel.exporter.jaeger.endpoint=http://tempo:14250
      - otel.metrics.exporter=none
      - otel.javaagent.debug=false
      - otel.resource.attributes=service.name=shipping-service-otel
    volumes:
      - ./data/applications/logs:/app/logs
    depends_on:
      - tempo

  promtail:
    image: grafana/promtail:2.2.0
    command: -config.file=/etc/promtail/promtail-local.yaml
    volumes:
      - ./configs/promtail/promtail-local.yaml:/etc/promtail/promtail-local.yaml
      - ./data/applications/logs:/app/logs
    depends_on:
      - order-service-otel
      - shipping-service-otel
      - loki

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9090:9090"
    depends_on:
      - order-service-otel
      - shipping-service-otel

  grafana:
    image: grafana/grafana:7.4.0-ubuntu
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo-query
      - loki