apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: storage-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - mountPath: /vol
          name: csi-hostpath-demo-vol
      volumes:
      - name: csi-hostpath-demo-vol
        persistentVolumeClaim:
          claimName: csi-hostpath-demo-pvc