apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-hostpath-demo-pvc
  namespace: storage-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-demo-sc