apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment-v2
  labels:
    app: order-service
    version: v2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
      version: v2
  template:
    metadata:
      labels:
        app: order-service
        version: v2
    spec:
      serviceAccountName: order-service-sa
      containers:
        - name: order-service-container-v1
          image: sinhasonalkumar/order-orchestrator-service:v2
          imagePullPolicy: Always
          ports:
            - name: order-svc-port 
              containerPort: 8080
              #hostPort: 8080
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xms128m -Xmx512m"    
          resources:
            requests:
              memory: 130Mi
              cpu: 600m
            limits:
              memory: 520Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: order-svc-port
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 4
          livenessProbe:
            httpGet:
              path: /order-service/actuator/health
              port: order-svc-port
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 4
          # startupProbe:
          #  httpGet:
          #    path: /order-service/actuator/health
          #    port: order-svc-port
          #  initialDelaySeconds: 15
          #  periodSeconds: 20