apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: product-service-auth-policy
  namespace: default
spec:  
  selector:
    matchLabels:
      app: product-service