apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment-v2
  labels:
    app: order-service
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
      version: v2
  template:
    metadata:
      labels:
        app: order-service
        version: v2
    spec:
      serviceAccountName: order-service-sa
      containers:
        - name: order-service-container-v2
          image: sinhasonalkumar/order-orchestrator-service:vCookie
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---