apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    service: order-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort : 8080
      name: http
  selector:
    app: order-service