apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    env:
      - name: MY_SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: app-in-sync-secret
            key: my_secret_key
            optional: false
    volumeMounts:
    - name: app-secret-vol
      mountPath: "/var/app-secret"
      readOnly: true
  volumes:
  - name: app-secret-vol
    secret:
      secretName: app-in-sync-secret
      optional: false
