apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: app-secret-vol
      mountPath: "/var/app-secret"
      readOnly: true
  volumes:
  - name: app-secret-vol
    secret:
      secretName: app-in-sync-secret
      optional: false
