apiVersion: v1
kind: Pod
metadata:
  name: buildah
spec:
  containers:
    - name: buildah-builder
      image: docker.io/buildah/buildah
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 3600; done"
      securityContext:
        privileged: true
        #runAsUser: 1000
  volumes:
  - name: build-context
    emptyDir: {}