apiVersion: v1
kind: Pod
metadata:
  name: podman
spec:
  containers:
    - name: podman-builder
      image: quay.io/podman/stable:latest  # Replace with the Podman image you want to use
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 3600; done"  # Keep the SSH container running
      securityContext:
        privileged: true
        runAsUser: 1000
  volumes:
  - name: build-context
    emptyDir: {}
