apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment
spec:
  selector:
    matchLabels:
      app: web-server
  replicas: 3
  template:
    metadata:
      labels:
        app: web-server
    spec:
      tolerations:
        - key: workLoad
          operator: "Equal"
          value: prod
          effect: NoSchedule
        - key: mem
          operator: "Equal"
          value: low
          effect: NoExecute
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: env
                  operator: NotIn 
                  values:
                    - dev     
      containers:
      - name: web-server-container
        image: nginx:1.21.0-alpine