apiVersion: v1
kind: Pod
metadata:
  name: dind-ssh-pod
spec:
  containers:
    - name: dind-container
      image: docker:20.10
      securityContext:
        privileged: true  # Enable privileged mode for Docker-in-Docker
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock  # Mount the Docker socket from the host
      command:
        - "/bin/sh"
        - "-c"
        - "while true; do sleep 3600; done"  # Keep the SSH container running
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock  # Path to the Docker socket on the host
