apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server-deployment
spec:
  selector:
    matchLabels:
      app: cache-server
  replicas: 3
  template:
    metadata:
      labels:
        app: cache-server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cache-server
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cache-server-container
        image: redis:6.2.4-alpine