apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-default-sa-deployment-v1
  labels:
    app: rbac-default-sa
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-default-sa
      version: v1
  template:
    metadata:
      labels:
        app: rbac-default-sa
        version: v1
    spec:
      containers:
        - name: rbac-default-sa-container-v1
          image: curlimages/curl
          imagePullPolicy: Always
          command: [ "sleep", "6000" ]