kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-access-kind-group
  namespace: default
roleRef:
  kind: Role
  name: reader-access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: devUsersGroup
  apiGroup: rbac.authorization.k8s.io