kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-access
  namespace: default
roleRef:
  kind: Role
  name: reader-access
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: devUser
  apiGroup: rbac.authorization.k8s.io